version: "3"
services:
  tad:
    image: postgres:9.6
    container_name: "postgres_sensei"
    environment:
      - POSTGRES_DB=tadpgweb
      - POSTGRES_USER=postgres
      - TZ=GMT
    volumes:
      - "./sensei_db.sql:/docker-entrypoint-initdb.d/sensei_db.sql"
    ports:
      - 5432:5432
    networks:
      - sensei-network
  dotnet:
    image: sensei_lab
    container_name: "sensei_api"
    build:
      context: ./sensei_api/sensei_api/
      dockerfile: Dockerfile
    ports:
      - 5003:80
    networks:
      - sensei-network
  sensei_front:
    image: node:10.9.0
    ports:
      - "80:3000"
    volumes:
      - ./sensei_front/sensei_front:/usr/src/app
    working_dir: /usr/src/app
    command:
      - /bin/bash
      - -c
      - rm -rf node_modules && yarn install --silent && yarn start
    networks:
      - sensei-network

networks: 
    sensei-network:
        driver: bridge
